/**
 * Sandbox dataset.
 *
 * Everything here stands in for Teambridge collections until the app is
 * pointed at a real account. Shifts are generated relative to the current
 * day so the board always has a same-day emergency, a this-week gap, and a
 * couple of already-covered shifts to show the loop closing.
 */
import type { Interpreter, Shift } from './types';

function dayStart(now: Date, dayOffset: number): Date {
  const d = new Date(now);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + dayOffset);
  return d;
}

/** ISO timestamp at `hour:minute` local, `dayOffset` days from today. */
function at(now: Date, dayOffset: number, hour: number, minute = 0): string {
  const d = dayStart(now, dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

/** Availability shorthand: `avail('mon-fri', 8, 18)`. */
function avail(days: number[], startHour: number, endHour: number) {
  return days.map((dayOfWeek) => ({
    dayOfWeek,
    startMinute: startHour * 60,
    endMinute: endHour * 60,
  }));
}

const WEEKDAYS = [1, 2, 3, 4, 5];
const ALL_DAYS = [0, 1, 2, 3, 4, 5, 6];
const WEEKEND = [0, 6];

export function buildInterpreters(now: Date): Interpreter[] {
  return [
    {
      id: 'int-avery',
      name: 'Avery Nakamura',
      employmentStatus: 'full-time',
      hireDate: '2019-03-11',
      homeRegion: 'Austin, TX',
      jurisdictions: ['TX', 'NM', 'OK', 'CO'],
      credentials: ['NIC-Advanced', 'Medical-Certified'],
      serviceLines: ['VRS', 'VRI', 'Medical'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 32,
      scheduledWeeklyHours: 26,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 48,
      availability: [...avail(WEEKDAYS, 7, 19), ...avail([6], 9, 15)],
      interests: ['VRS Evening', 'Medical'],
      reliability: 0.96,
      lastShiftEndAt: at(now, -1, 17),
      consecutiveDaysWorked: 2,
    },
    {
      id: 'int-marisol',
      name: 'Marisol Reyes',
      employmentStatus: 'full-time',
      hireDate: '2016-08-02',
      homeRegion: 'San Diego, CA',
      jurisdictions: ['CA', 'AZ'],
      credentials: ['NIC', 'Trilingual'],
      serviceLines: ['VRS', 'Community'],
      languages: ['ASL', 'English', 'Spanish', 'LSM'],
      committedWeeklyHours: 32,
      scheduledWeeklyHours: 34,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 45,
      availability: [...avail(WEEKDAYS, 6, 16)],
      interests: ['Trilingual', 'VRS Morning'],
      reliability: 0.93,
      lastShiftEndAt: at(now, 0, 6),
      consecutiveDaysWorked: 4,
    },
    {
      id: 'int-dee',
      name: 'Dee Whitfield',
      employmentStatus: 'full-time',
      hireDate: '2014-01-20',
      homeRegion: 'Austin, TX',
      jurisdictions: ['TX', 'LA'],
      credentials: ['CDI', 'NIC'],
      serviceLines: ['VRS', 'Community', 'Legal'],
      languages: ['ASL'],
      committedWeeklyHours: 30,
      scheduledWeeklyHours: 18,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 40,
      availability: [...avail(ALL_DAYS, 8, 22)],
      interests: ['VRS Evening', 'Legal', 'DeafBlind'],
      reliability: 0.99,
      lastShiftEndAt: at(now, -2, 20),
      consecutiveDaysWorked: 0,
    },
    {
      id: 'int-priya',
      name: 'Priya Raghunathan',
      employmentStatus: 'part-time',
      hireDate: '2021-06-14',
      homeRegion: 'Toronto, ON',
      jurisdictions: ['ON', 'QC'],
      credentials: ['NIC'],
      serviceLines: ['VRS', 'VRI'],
      languages: ['ASL', 'English', 'LSQ'],
      committedWeeklyHours: 20,
      scheduledWeeklyHours: 12,
      overtimeThresholdHours: 44,
      maxWeeklyHours: 40,
      availability: [...avail(WEEKDAYS, 9, 21)],
      interests: ['VRS Evening', 'Canada'],
      reliability: 0.91,
      lastShiftEndAt: at(now, -1, 15),
      consecutiveDaysWorked: 1,
    },
    {
      id: 'int-jonah',
      name: 'Jonah Feldman',
      employmentStatus: 'per-diem',
      hireDate: '2023-02-27',
      homeRegion: 'Austin, TX',
      jurisdictions: ['TX'],
      credentials: ['NIC'],
      serviceLines: ['VRS'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 0,
      scheduledWeeklyHours: 8,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 30,
      availability: [...avail(WEEKDAYS, 13, 23), ...avail(WEEKEND, 10, 22)],
      interests: ['VRS Evening'],
      reliability: 0.84,
      lastShiftEndAt: at(now, -3, 22),
      consecutiveDaysWorked: 0,
    },
    {
      id: 'int-tasha',
      name: 'Tasha Boone',
      employmentStatus: 'full-time',
      hireDate: '2018-11-05',
      homeRegion: 'Phoenix, AZ',
      jurisdictions: ['AZ', 'NV', 'CA'],
      credentials: ['NIC-Advanced', 'Legal-Certified'],
      serviceLines: ['VRS', 'Legal', 'Community'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 32,
      scheduledWeeklyHours: 38,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 48,
      availability: [...avail(WEEKDAYS, 7, 18)],
      interests: ['Legal'],
      reliability: 0.97,
      lastShiftEndAt: at(now, 0, 12),
      consecutiveDaysWorked: 5,
    },
    {
      id: 'int-kwame',
      name: 'Kwame Osei',
      employmentStatus: 'part-time',
      hireDate: '2022-09-19',
      homeRegion: 'Chicago, IL',
      jurisdictions: ['IL', 'IN', 'WI', 'CO'],
      credentials: ['NIC', 'Medical-Certified'],
      serviceLines: ['VRS', 'VRI', 'Medical'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 24,
      scheduledWeeklyHours: 15,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 35,
      availability: [...avail([1, 2, 3, 4, 5, 6], 8, 23)],
      interests: ['VRS Evening', 'Medical', 'Same-day'],
      reliability: 0.95,
      lastShiftEndAt: at(now, -1, 21),
      consecutiveDaysWorked: 3,
    },
    {
      id: 'int-lena',
      name: 'Lena Ostrowski',
      employmentStatus: 'full-time',
      hireDate: '2020-04-30',
      homeRegion: 'Denver, CO',
      jurisdictions: ['CO', 'UT', 'NM'],
      credentials: ['NIC', 'Medical-Certified'],
      serviceLines: ['VRS', 'Medical', 'VRI'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 32,
      scheduledWeeklyHours: 29,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 44,
      availability: [...avail(WEEKDAYS, 6, 17)],
      interests: ['Medical', 'VRS Morning'],
      reliability: 0.94,
      lastShiftEndAt: at(now, -1, 16),
      consecutiveDaysWorked: 2,
    },
    {
      id: 'int-rafael',
      name: 'Rafael Duarte',
      employmentStatus: 'per-diem',
      hireDate: '2024-01-08',
      homeRegion: 'San Diego, CA',
      jurisdictions: ['CA'],
      credentials: ['NIC', 'Trilingual'],
      serviceLines: ['VRS', 'Community'],
      languages: ['ASL', 'English', 'Spanish'],
      committedWeeklyHours: 0,
      scheduledWeeklyHours: 4,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 24,
      availability: [...avail([0, 5, 6], 8, 20), ...avail([3], 17, 23)],
      interests: ['Trilingual', 'Same-day'],
      reliability: 0.88,
      lastShiftEndAt: at(now, -4, 19),
      consecutiveDaysWorked: 0,
    },
    {
      id: 'int-yuki',
      name: 'Yuki Tran',
      employmentStatus: 'full-time',
      hireDate: '2017-05-22',
      homeRegion: 'Vancouver, BC',
      jurisdictions: ['BC', 'AB'],
      credentials: ['NIC-Advanced'],
      serviceLines: ['VRS', 'VRI', 'Community'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 30,
      scheduledWeeklyHours: 22,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 44,
      availability: [...avail(ALL_DAYS, 7, 20)],
      interests: ['Canada', 'VRS Morning'],
      reliability: 0.98,
      lastShiftEndAt: at(now, -2, 18),
      consecutiveDaysWorked: 1,
    },
    {
      id: 'int-brandon',
      name: 'Brandon Cole',
      employmentStatus: 'part-time',
      hireDate: '2023-10-02',
      homeRegion: 'Austin, TX',
      jurisdictions: ['TX', 'AR'],
      credentials: ['NIC'],
      serviceLines: ['VRS'],
      languages: ['ASL', 'English'],
      committedWeeklyHours: 20,
      scheduledWeeklyHours: 19,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 32,
      availability: [...avail(WEEKDAYS, 12, 22), ...avail(WEEKEND, 9, 18)],
      interests: ['VRS Evening', 'Same-day'],
      reliability: 0.9,
      lastShiftEndAt: at(now, 0, 2),
      consecutiveDaysWorked: 2,
    },
    {
      id: 'int-simone',
      name: 'Simone Baptiste',
      employmentStatus: 'full-time',
      hireDate: '2015-07-13',
      homeRegion: 'Montréal, QC',
      jurisdictions: ['QC', 'ON'],
      credentials: ['NIC', 'CDI'],
      serviceLines: ['VRS', 'Community', 'Legal'],
      languages: ['ASL', 'LSQ', 'French', 'English'],
      committedWeeklyHours: 32,
      scheduledWeeklyHours: 24,
      overtimeThresholdHours: 40,
      maxWeeklyHours: 40,
      availability: [...avail(WEEKDAYS, 8, 20)],
      interests: ['Canada', 'Legal'],
      reliability: 0.96,
      lastShiftEndAt: at(now, -1, 19),
      consecutiveDaysWorked: 3,
    },
  ];
}

export function buildShifts(now: Date): Shift[] {
  const hour = now.getHours();
  /** Keep the "same-day emergency" genuinely later today, whenever today is. */
  const emergencyStart = Math.min(Math.max(hour + 3, 10), 20);

  return [
    {
      id: 'shift-4821',
      code: 'VRS-4821',
      startAt: at(now, 0, emergencyStart),
      endAt: at(now, 0, emergencyStart + 4),
      serviceLine: 'VRS',
      queue: 'VRS Evening',
      jurisdiction: 'TX',
      site: 'Remote — Austin queue',
      requiredCredentials: ['NIC'],
      requiredLanguages: ['ASL'],
      origin: 'callout',
      calloutReason: 'Illness',
      previousInterpreterId: 'int-tasha',
      billableMinutesForecast: 186,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, 0, Math.max(hour - 1, 0), 20),
    },
    {
      id: 'shift-4822',
      code: 'VRI-4822',
      startAt: at(now, 1, 9),
      endAt: at(now, 1, 15),
      serviceLine: 'Medical',
      queue: 'Medical VRI',
      jurisdiction: 'CO',
      site: 'Remote — Denver',
      requiredCredentials: ['Medical-Certified'],
      requiredLanguages: ['ASL'],
      origin: 'callout',
      calloutReason: 'Family emergency',
      previousInterpreterId: 'int-lena',
      billableMinutesForecast: 268,
      status: 'offers-out',
      assignedInterpreterId: null,
      offers: [
        { interpreterId: 'int-kwame', state: 'viewed', at: at(now, 0, 8, 12) },
        { interpreterId: 'int-avery', state: 'sent', at: at(now, 0, 8, 12) },
      ],
      openedAt: at(now, -1, 19, 40),
    },
    {
      id: 'shift-4823',
      code: 'VRS-4823',
      startAt: at(now, 2, 16),
      endAt: at(now, 2, 22),
      serviceLine: 'VRS',
      queue: 'VRS Evening',
      jurisdiction: 'TX',
      site: 'Remote — Austin queue',
      requiredCredentials: ['NIC'],
      requiredLanguages: ['ASL'],
      origin: 'unfilled',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 291,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, -2, 9),
    },
    {
      id: 'shift-4824',
      code: 'VRS-4824',
      startAt: at(now, 3, 8),
      endAt: at(now, 3, 14),
      serviceLine: 'VRS',
      queue: 'VRS Morning — Trilingual',
      jurisdiction: 'CA',
      site: 'Remote — San Diego',
      requiredCredentials: ['Trilingual'],
      requiredLanguages: ['ASL', 'Spanish'],
      origin: 'demand-spike',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 302,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, -1, 11, 15),
    },
    {
      id: 'shift-4825',
      code: 'LEG-4825',
      startAt: at(now, 4, 13),
      endAt: at(now, 4, 17),
      serviceLine: 'Legal',
      queue: 'Legal — deposition',
      jurisdiction: 'AZ',
      site: 'Phoenix — client site',
      requiredCredentials: ['Legal-Certified'],
      requiredLanguages: ['ASL'],
      origin: 'unfilled',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 210,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, -3, 14),
    },
    {
      id: 'shift-4826',
      code: 'VRS-4826',
      startAt: at(now, 5, 10),
      endAt: at(now, 5, 16),
      serviceLine: 'VRS',
      queue: 'VRS Morning — Canada',
      jurisdiction: 'ON',
      site: 'Remote — Toronto queue',
      requiredCredentials: ['NIC'],
      requiredLanguages: ['ASL'],
      origin: 'unfilled',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 254,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, -2, 16, 30),
    },
    {
      id: 'shift-4827',
      code: 'VRS-4827',
      startAt: at(now, 6, 18),
      endAt: at(now, 6, 23),
      serviceLine: 'VRS',
      queue: 'VRS Evening',
      jurisdiction: 'IL',
      site: 'Remote — Chicago queue',
      requiredCredentials: ['NIC'],
      requiredLanguages: ['ASL'],
      origin: 'demand-spike',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 238,
      status: 'open',
      assignedInterpreterId: null,
      offers: [],
      openedAt: at(now, 0, 7, 5),
    },
    {
      id: 'shift-4815',
      code: 'VRS-4815',
      startAt: at(now, 1, 12),
      endAt: at(now, 1, 18),
      serviceLine: 'VRS',
      queue: 'VRS Midday',
      jurisdiction: 'BC',
      site: 'Remote — Vancouver queue',
      requiredCredentials: ['NIC'],
      requiredLanguages: ['ASL'],
      origin: 'callout',
      calloutReason: 'Schedule conflict',
      previousInterpreterId: 'int-simone',
      billableMinutesForecast: 276,
      status: 'filled',
      assignedInterpreterId: 'int-yuki',
      offers: [
        { interpreterId: 'int-yuki', state: 'accepted', at: at(now, -2, 10, 6) },
        { interpreterId: 'int-priya', state: 'sent', at: at(now, -2, 10, 4) },
      ],
      openedAt: at(now, -2, 10, 2),
    },
    {
      id: 'shift-4816',
      code: 'MED-4816',
      startAt: at(now, 2, 8),
      endAt: at(now, 2, 12),
      serviceLine: 'Medical',
      queue: 'Medical VRI',
      jurisdiction: 'IL',
      site: 'Remote — Chicago',
      requiredCredentials: ['Medical-Certified'],
      requiredLanguages: ['ASL'],
      origin: 'unfilled',
      calloutReason: null,
      previousInterpreterId: null,
      billableMinutesForecast: 194,
      status: 'filled',
      assignedInterpreterId: 'int-kwame',
      offers: [{ interpreterId: 'int-kwame', state: 'accepted', at: at(now, -1, 13, 22) }],
      openedAt: at(now, -1, 13, 8),
    },
  ];
}
